package EntornoGrafico;

import Base_de_datos.Conexion;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Res
 */
public class Modificar_Provedor extends javax.swing.JFrame
{ 
Conexion conex = new Conexion();
 Connection cone2;


private void EliminarRegistro()

{
    cone2=conex.CargarDB_Base_datos_Provedores();
   if(cone2!=null) {
        try
        {
       String TextoFantasma=jTextField1_txtNombreApellido_Provedor.getText();
            try ( // Esto sirve para eleminar y actualizar vista de datos de la tabla.!! :9
                    Statement orden = cone2.createStatement())
            {
                String Eliminar = "Delete From ListadeProvedores  Where Codigo_Provedor="+jTextField1_txtCodigo_Provedor.getText();
                orden.executeUpdate (Eliminar);       
            }
       PropiedadesTabla();
       jComboBox_BuscarporCodProvedor.removeAllItems();
    

       ComboCodigosProvedor();  
       
      
       
       JOptionPane.showMessageDialog(this, "El Provedor: ("+TextoFantasma+") se ha Eliminado con Exito");
        }
        catch (SQLException ex)
        {
        JOptionPane.showMessageDialog(this, "Error, no se pudo eliminar el registro: "+ex);
        }
       
   }
}

 
 
 
/**
 * Creates new form Modificar_Provedor
 */
public Modificar_Provedor()
{
    initComponents();
    conex.CrearDB_Base_datos_Provedores();
    cone2=conex.CargarDB_Base_datos_Provedores();
   if(cone2!=null)
   {
      PropiedadesTabla();
      ComboCodigosProvedor();
   }
}


/**
 * This method is called from within the constructor to
 * initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
 * always regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton1_CerrarVentanAbierta = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2_Codigo_Cliente = new javax.swing.JLabel();
        jTextField1_txtCodigo_Provedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1_txtNombreApellido_Provedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1_txtCalle_Provedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_txtCalle_Numero_Provedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1_txtTelefonoFijo_Provedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2_txtTelefonoMovil_Provedor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1_TablaProvedor = new javax.swing.JTable();
        jComboBox_BuscarporCodProvedor = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1_txtPiso_Provedor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField1_txtEntreCalles_Provedor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField1_txtGoogleMaps_Provedor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField1_txtCODPOSTAL_Provedor = new javax.swing.JTextField();
        jTextField1_txtProvincia_Provedor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1_txtCiudad_Provedor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField1_txtEmail_Provedor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_txtAnotacionl_Provedor = new javax.swing.JTextArea();
        jButton_Buscar = new javax.swing.JButton();
        jTextField1_Texto_a_Buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2_eleminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1_CerrarVentanAbierta.setText("Cerrar");
        jButton1_CerrarVentanAbierta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_CerrarVentanAbiertaActionPerformed(evt);
            }
        });

        jLabel2_Codigo_Cliente.setText("Código:");

        jTextField1_txtCodigo_Provedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1_txtCodigo_Provedor.setText("000");
        jTextField1_txtCodigo_Provedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1_txtCodigo_ProvedorActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre y Apellido:");

        jTextField1_txtNombreApellido_Provedor.setToolTipText("Campo Mínimo requerido (Requerido)");
        jTextField1_txtNombreApellido_Provedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1_txtNombreApellido_ProvedorActionPerformed(evt);
            }
        });

        jLabel3.setText("Calle:");

        jTextField1_txtCalle_Provedor.setToolTipText("Campo Mínimo requerido (Requerido)");

        jLabel6.setText("Numero:");

        jTextField1_txtCalle_Numero_Provedor.setToolTipText("Campo Mínimo requerido (Requerido)");

        jLabel4.setText("Teléfono Fijo:");

        jTextField1_txtTelefonoFijo_Provedor.setToolTipText("Campo Mínimo requerido (Requerido)");

        jLabel5.setText("Celular:");

        jTextField2_txtTelefonoMovil_Provedor.setToolTipText("Campo Mínimo requerido (Requerido)");
        jTextField2_txtTelefonoMovil_Provedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField2_txtTelefonoMovil_ProvedorActionPerformed(evt);
            }
        });

        jTable1_TablaProvedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jTable1_TablaProvedor.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTable1_TablaProvedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1_TablaProvedor);

        jComboBox_BuscarporCodProvedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox_BuscarporCodProvedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1_txtNombreApellido_Provedor)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1_txtCalle_Provedor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1_txtCalle_Numero_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1_txtTelefonoFijo_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2_txtTelefonoMovil_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(285, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2_Codigo_Cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1_txtCodigo_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_BuscarporCodProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_Codigo_Cliente)
                    .addComponent(jTextField1_txtCodigo_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_BuscarporCodProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1_txtNombreApellido_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1_txtCalle_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1_txtCalle_Numero_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1_txtTelefonoFijo_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2_txtTelefonoMovil_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Datos Basicos", jPanel1);

        jLabel7.setText("Piso / Depto :");

        jTextField1_txtPiso_Provedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1_txtPiso_ProvedorActionPerformed(evt);
            }
        });

        jLabel8.setText("Entre Calles :");

        jLabel9.setText("GoogleMaps :");

        jLabel10.setText("Código Postal :");

        jLabel12.setText("Provincia :");

        jLabel13.setText("Ciudad :");

        jLabel14.setText("E-mail:");

        jTextField1_txtEmail_Provedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1_txtEmail_ProvedorActionPerformed(evt);
            }
        });

        jLabel11.setText("Anotación (Un bloque de texto Libre):");

        jTextArea1_txtAnotacionl_Provedor.setColumns(20);
        jTextArea1_txtAnotacionl_Provedor.setRows(5);
        jScrollPane1.setViewportView(jTextArea1_txtAnotacionl_Provedor);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1_txtPiso_Provedor, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(jTextField1_txtEntreCalles_Provedor)
                            .addComponent(jTextField1_txtGoogleMaps_Provedor)
                            .addComponent(jTextField1_txtEmail_Provedor)
                            .addComponent(jTextField1_txtCiudad_Provedor)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField1_txtCODPOSTAL_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1_txtProvincia_Provedor, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))))
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1_txtPiso_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1_txtEntreCalles_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1_txtGoogleMaps_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField1_txtCODPOSTAL_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField1_txtProvincia_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField1_txtCiudad_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField1_txtEmail_Provedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Datos Opcionales", jPanel2);

        jButton_Buscar.setText("Buscar");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_BuscarActionPerformed(evt);
            }
        });

        jTextField1_Texto_a_Buscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1_Texto_a_Buscar.setText("(Ingrese el Código)");
        jTextField1_Texto_a_Buscar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTextField1_Texto_a_BuscarMouseClicked(evt);
            }
        });
        jTextField1_Texto_a_Buscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1_Texto_a_BuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Modificar y Buscar Provedores");

        jButton1.setText("Modificar Registro");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2_eleminar.setText("Eliminar Registro");
        jButton2_eleminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2_eleminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1_Texto_a_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1_CerrarVentanAbierta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2_eleminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1_Texto_a_Buscar)
                    .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2_eleminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1_CerrarVentanAbierta)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_CerrarVentanAbiertaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_CerrarVentanAbiertaActionPerformed
    {//GEN-HEADEREND:event_jButton1_CerrarVentanAbiertaActionPerformed
        // Clic Boton Cerrar
//  Java: dispose() es usado para cerrar un jframe
        dispose();
    }//GEN-LAST:event_jButton1_CerrarVentanAbiertaActionPerformed

    private void jTextField1_txtPiso_ProvedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1_txtPiso_ProvedorActionPerformed
    {//GEN-HEADEREND:event_jTextField1_txtPiso_ProvedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_txtPiso_ProvedorActionPerformed

    private void jTextField1_txtEmail_ProvedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1_txtEmail_ProvedorActionPerformed
    {//GEN-HEADEREND:event_jTextField1_txtEmail_ProvedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_txtEmail_ProvedorActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_BuscarActionPerformed
    {//GEN-HEADEREND:event_jButton_BuscarActionPerformed
//Conexion conex = new Conexion();
//Connection cone2;
 cone2= conex.CargarDB_Base_datos_Provedores();
 if(cone2!=null)
 {
     try
     {
         Statement orden = cone2.createStatement();
         ResultSet r = orden.executeQuery("Select* From ListadeProvedores Where Codigo_Provedor="+jTextField1_Texto_a_Buscar.getText());
         if(r.next())
         {
          jTextField1_txtCodigo_Provedor.setText(r.getString("Codigo_Provedor"));
          jTextField1_txtNombreApellido_Provedor.setText(r.getString("NombreyApellidoProvedor"));
          jTextField1_txtCalle_Provedor.setText(r.getString("Calle_Provedor"));
          jTextField1_txtCalle_Numero_Provedor.setText(r.getString("Calle_Numero_Provedor"));          
          jTextField1_txtTelefonoFijo_Provedor.setText(r.getString("TelefonoFijo_Provedor"));
          jTextField2_txtTelefonoMovil_Provedor.setText(r.getString("TelefonoMovil_Provedor")); 
          jTextField1_txtPiso_Provedor.setText(r.getString("Piso_Provedor")); 
          jTextField1_txtEntreCalles_Provedor.setText(r.getString("EntreCalles_Provedor")); 
          jTextField1_txtGoogleMaps_Provedor.setText(r.getString("GoogleMaps_Provedor")); 
          jTextField1_txtCODPOSTAL_Provedor.setText(r.getString("CODPOSTAL_Provedor")); 
          jTextField1_txtProvincia_Provedor.setText(r.getString("Provincia_Provedor")); 
          jTextField1_txtCiudad_Provedor.setText(r.getString("Ciudad_Provedor")); 
          jTextField1_txtEmail_Provedor.setText(r.getString("Email_Provedor")); 
          jTextArea1_txtAnotacionl_Provedor.setText(r.getString("Anotacionl_Provedor"));
             r.close();
             orden.close();
         }
     }
     catch (SQLException ex)
     {
         Logger.getLogger(Modificar_Provedor.class.getName()).log(Level.SEVERE, null, ex);
         System.out.println("41");
     }
 }



    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jTextField1_Texto_a_BuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1_Texto_a_BuscarActionPerformed
    {//GEN-HEADEREND:event_jTextField1_Texto_a_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_Texto_a_BuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
//Boton Modificar registro
if (jTextField1_txtCodigo_Provedor.getText().equals(""))
        {
            JOptionPane.showInputDialog(this,"Codigo de Provedor Vacio");
        }else
            {
              Editar_Registro();  
            }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2_eleminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2_eleminarActionPerformed
    {//GEN-HEADEREND:event_jButton2_eleminarActionPerformed
        if (jTextField1_txtCodigo_Provedor.getText().equals(""))
        {
JOptionPane.showMessageDialog(this,"El campo de Codigo de Provedor esta Vacio");
        } else 
        {
       // el codigo indica los botones de eleminar y cancelar tomando el codigo JOtionPane. la option Yes.Option es el primier boton o el de okey
       // La segunda NO_Option seria el boton cancelar o el 2 boton     
        String opcion[] = {"Eliminar", "Cancelar"};
        String TextoFantasma=jTextField1_txtNombreApellido_Provedor.getText();
        int eleccion = JOptionPane.showOptionDialog(this, "¿Quieres eliminar (" +TextoFantasma+ ") ?", "Eliminar registro", 0, 0, null, opcion, evt);
            if (eleccion==JOptionPane.YES_OPTION)
            {
                EliminarRegistro();
          
            
            
            }
            else if (eleccion==JOptionPane.NO_OPTION) 
            { 
                
            }
            }
    
    }//GEN-LAST:event_jButton2_eleminarActionPerformed

    private void jComboBox_BuscarporCodProvedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox_BuscarporCodProvedorActionPerformed
    {//GEN-HEADEREND:event_jComboBox_BuscarporCodProvedorActionPerformed
        //Conexion conex = new Conexion();
        //Connection cone2;

        cone2= conex.CargarDB_Base_datos_Provedores();
        if(cone2!=null)
        {
            try
            {
                Statement orden = cone2.createStatement();
                ResultSet r = orden.executeQuery("Select* From ListadeProvedores Where Codigo_Provedor="+jComboBox_BuscarporCodProvedor.getSelectedItem());
                if(r.next())
                {
                    jTextField1_txtCodigo_Provedor.setText(r.getString("Codigo_Provedor"));
                    jTextField1_txtNombreApellido_Provedor.setText(r.getString("NombreyApellidoProvedor"));
                    jTextField1_txtCalle_Provedor.setText(r.getString("Calle_Provedor"));
                    jTextField1_txtCalle_Numero_Provedor.setText(r.getString("Calle_Numero_Provedor"));
                    jTextField1_txtTelefonoFijo_Provedor.setText(r.getString("TelefonoFijo_Provedor"));
                    jTextField2_txtTelefonoMovil_Provedor.setText(r.getString("TelefonoMovil_Provedor"));
                    jTextField1_txtPiso_Provedor.setText(r.getString("Piso_Provedor"));
                    jTextField1_txtEntreCalles_Provedor.setText(r.getString("EntreCalles_Provedor"));
                    jTextField1_txtGoogleMaps_Provedor.setText(r.getString("GoogleMaps_Provedor"));
                    jTextField1_txtCODPOSTAL_Provedor.setText(r.getString("CODPOSTAL_Provedor"));
                    jTextField1_txtProvincia_Provedor.setText(r.getString("Provincia_Provedor"));
                    jTextField1_txtCiudad_Provedor.setText(r.getString("Ciudad_Provedor"));
                    jTextField1_txtEmail_Provedor.setText(r.getString("Email_Provedor"));
                    jTextArea1_txtAnotacionl_Provedor.setText(r.getString("Anotacionl_Provedor"));
                    r.close();
                    orden.close();
                }
            }
            catch (SQLException ex)
            {
                Logger.getLogger(Modificar_Provedor.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("41");
            }
        }
    }//GEN-LAST:event_jComboBox_BuscarporCodProvedorActionPerformed

    private void jTextField2_txtTelefonoMovil_ProvedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField2_txtTelefonoMovil_ProvedorActionPerformed
    {//GEN-HEADEREND:event_jTextField2_txtTelefonoMovil_ProvedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_txtTelefonoMovil_ProvedorActionPerformed

    private void jTextField1_txtNombreApellido_ProvedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1_txtNombreApellido_ProvedorActionPerformed
    {//GEN-HEADEREND:event_jTextField1_txtNombreApellido_ProvedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_txtNombreApellido_ProvedorActionPerformed

    private void jTextField1_txtCodigo_ProvedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1_txtCodigo_ProvedorActionPerformed
    {//GEN-HEADEREND:event_jTextField1_txtCodigo_ProvedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_txtCodigo_ProvedorActionPerformed

    private void jTable1_TablaProvedorMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTable1_TablaProvedorMouseClicked
    {//GEN-HEADEREND:event_jTable1_TablaProvedorMouseClicked
// al cliquear la tabla va tomar datos y mostrar en formulario
     int seleccion=jTable1_TablaProvedor.rowAtPoint(evt.getPoint());
     
     jTextField1_txtCodigo_Provedor.setText(String.valueOf(jTable1_TablaProvedor.getValueAt(seleccion, 0)));
     jTextField1_txtNombreApellido_Provedor.setText (String.valueOf(jTable1_TablaProvedor.getValueAt(seleccion, 1)));
     jTextField1_txtCalle_Provedor.setText (String.valueOf(jTable1_TablaProvedor.getValueAt(seleccion, 2)));
     jTextField1_txtCalle_Numero_Provedor.setText (String.valueOf(jTable1_TablaProvedor.getValueAt(seleccion, 3)));
     jTextField1_txtTelefonoFijo_Provedor.setText (String.valueOf(jTable1_TablaProvedor.getValueAt(seleccion, 4))); 
     jTextField2_txtTelefonoMovil_Provedor.setText (String.valueOf(jTable1_TablaProvedor.getValueAt(seleccion, 5)));
     jTextField1_txtPiso_Provedor.setText (String.valueOf(jTable1_TablaProvedor.getValueAt(seleccion, 6)));    
     jTextField1_txtEntreCalles_Provedor.setText (String.valueOf(jTable1_TablaProvedor.getValueAt(seleccion, 7)));
     jTextField1_txtGoogleMaps_Provedor.setText (String.valueOf(jTable1_TablaProvedor.getValueAt(seleccion, 8)));
     jTextField1_txtCODPOSTAL_Provedor.setText (String.valueOf(jTable1_TablaProvedor.getValueAt(seleccion, 9)));
     jTextField1_txtProvincia_Provedor.setText (String.valueOf(jTable1_TablaProvedor.getValueAt(seleccion, 10)));    
     jTextField1_txtCiudad_Provedor.setText (String.valueOf(jTable1_TablaProvedor.getValueAt(seleccion, 11))); 
     jTextField1_txtEmail_Provedor.setText (String.valueOf(jTable1_TablaProvedor.getValueAt(seleccion, 12))); 
     jTextArea1_txtAnotacionl_Provedor.setText (String.valueOf(jTable1_TablaProvedor.getValueAt(seleccion, 13)));
     
        
    }//GEN-LAST:event_jTable1_TablaProvedorMouseClicked

    private void jTextField1_Texto_a_BuscarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTextField1_Texto_a_BuscarMouseClicked
    {//GEN-HEADEREND:event_jTextField1_Texto_a_BuscarMouseClicked
           jTextField1_Texto_a_Buscar.setText("");
    }//GEN-LAST:event_jTextField1_Texto_a_BuscarMouseClicked

/**
 * @param args the command line arguments
 */
public static void main(String args[])
{
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
        {
            if ("Nimbus".equals(info.getName()))
            {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    }
    catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
    {
        java.util.logging.Logger.getLogger(Modificar_Provedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() ->
    {
        new Modificar_Provedor().setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_CerrarVentanAbierta;
    private javax.swing.JButton jButton2_eleminar;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JComboBox<String> jComboBox_BuscarporCodProvedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_Codigo_Cliente;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1_TablaProvedor;
    private javax.swing.JTextArea jTextArea1_txtAnotacionl_Provedor;
    private javax.swing.JTextField jTextField1_Texto_a_Buscar;
    private javax.swing.JTextField jTextField1_txtCODPOSTAL_Provedor;
    private javax.swing.JTextField jTextField1_txtCalle_Numero_Provedor;
    private javax.swing.JTextField jTextField1_txtCalle_Provedor;
    private javax.swing.JTextField jTextField1_txtCiudad_Provedor;
    private javax.swing.JTextField jTextField1_txtCodigo_Provedor;
    private javax.swing.JTextField jTextField1_txtEmail_Provedor;
    private javax.swing.JTextField jTextField1_txtEntreCalles_Provedor;
    private javax.swing.JTextField jTextField1_txtGoogleMaps_Provedor;
    private javax.swing.JTextField jTextField1_txtNombreApellido_Provedor;
    private javax.swing.JTextField jTextField1_txtPiso_Provedor;
    private javax.swing.JTextField jTextField1_txtProvincia_Provedor;
    private javax.swing.JTextField jTextField1_txtTelefonoFijo_Provedor;
    private javax.swing.JTextField jTextField2_txtTelefonoMovil_Provedor;
    // End of variables declaration//GEN-END:variables

    private void Editar_Registro()
    {
       cone2=conex.CargarDB_Base_datos_Provedores();
       
       if (cone2!=null)
       {
           try    
           {
               Statement orden = cone2.createStatement();
               String editar="Update ListadeProvedores set "
                        + "NombreyApellidoProvedor='"+jTextField1_txtNombreApellido_Provedor.getText()+"',"
                        + "Calle_Provedor='"+jTextField1_txtCalle_Provedor.getText()+"',"
                        + "Calle_Numero_Provedor="+jTextField1_txtCalle_Numero_Provedor.getText()+","
                        + "TelefonoFijo_Provedor="+jTextField1_txtTelefonoFijo_Provedor.getText()+","
                        + "TelefonoMovil_Provedor="+jTextField2_txtTelefonoMovil_Provedor.getText()+","
                        + "Piso_Provedor='"+jTextField1_txtPiso_Provedor.getText()+"',"
                        + "EntreCalles_Provedor='"+jTextField1_txtEntreCalles_Provedor.getText()+"',"
                        + "GoogleMaps_Provedor='"+jTextField1_txtGoogleMaps_Provedor.getText()+"',"
                        + "CODPOSTAL_Provedor='"+jTextField1_txtCODPOSTAL_Provedor.getText()+"',"
                        + "Provincia_Provedor='"+jTextField1_txtProvincia_Provedor.getText()+"',"
                        + "Ciudad_Provedor='"+jTextField1_txtCiudad_Provedor.getText()+"',"
                        + "Email_Provedor='"+jTextField1_txtEmail_Provedor.getText()+"',"
                        + "Anotacionl_Provedor='"+jTextArea1_txtAnotacionl_Provedor.getText()+"'"
                       + "Where Codigo_Provedor="+jTextField1_txtCodigo_Provedor.getText();
               
               orden.executeUpdate(editar);
               JOptionPane.showMessageDialog(this, "El Registro ("+jTextField1_txtNombreApellido_Provedor.getText()+") se ha Modificado");
               PropiedadesTabla();
           }
           catch (SQLException ex)
           {
           JOptionPane.showMessageDialog(this, "No se puede Modificar el registro:"+ex);
           }
       }
        
    }
    
    private void PropiedadesTabla()
 {
     String Columnas[]=
     {
         "cod",
         "Nombre y Apellido",
         "Calle",
         "Altura",
         "Teléfono",
         "Celular",
         "Piso",
         "Entre Calles",
         "GoogleMaps",
         "CP",
         "Provincia",
         "Ciudad",
         "E-mail",
         "Nota"
     };
     DefaultTableModel dft = new DefaultTableModel(null,Columnas);
     
     try
     {
         Statement orden = cone2.createStatement();
         ResultSet r=orden.executeQuery("Select* From ListadeProvedores");
         
         while(r.next())
         {
         Object Filas[] = 
         {
             r.getString("Codigo_Provedor"),
             r.getString("NombreyApellidoProvedor"),
             r.getString("Calle_Provedor"),
             r.getString("Calle_Numero_Provedor"),
             r.getString("TelefonoFijo_Provedor"),
             r.getString("TelefonoMovil_Provedor"),
             r.getString("Piso_Provedor"),
             r.getString("EntreCalles_Provedor"),
             r.getString("GoogleMaps_Provedor"),
             r.getString("CODPOSTAL_Provedor"),
             r.getString("Provincia_Provedor"),
             r.getString("Ciudad_Provedor"),
             r.getString("Email_Provedor"),
             r.getString("Anotacionl_Provedor")
         };
         dft.addRow(Filas);
         }
         jTable1_TablaProvedor.setModel(dft);
     }
     catch (SQLException ex)
     {
         Logger.getLogger(Provedores_Agregar.class.getName()).log(Level.SEVERE, null, ex);
         System.out.println("No Anda Carga de la tabla: "+ex);
     }
     
 }
private void ComboCodigosProvedor()
{
    try 
    {
        Statement orden = cone2.createStatement();
        ResultSet r=orden.executeQuery("Select* from ListadeProvedores");
        while (r.next())
        {    
            jComboBox_BuscarporCodProvedor.addItem(r.getString("Codigo_Provedor"));
        }
    }
    catch (SQLException ex)
    {
        Logger.getLogger(Modificar_Provedor.class.getName()).log(Level.SEVERE, null, ex);
    }
}}
