/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EntornoGrafico;

// Importo la relación con la base de datos
import CodigoFuente.Conexion;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Res
 */
public class Ventana_Categorias extends javax.swing.JFrame
{
// Cargo la relación con la base de datos
     Conexion conex = new Conexion();
    Connection cone2;
   
    int contador_de_filas=0;
/**
 * Creates new form Ventana_Categorias
 */
private void IniciarContador(int contador_de_filas)
{
String columnas[] = {};

// Primero toma las filas pero no las tengo y pongo null
// Constructor de la Tabla
DefaultTableModel dft = new DefaultTableModel(null,columnas);
         try
         {
             Statement orden = cone2.createStatement();

//Monstrar Algo de una Base de Datos:

            ResultSet r = orden.executeQuery("Select* From Lista_de_Categorias");
            
             while (r.next())
             {  
                contador_de_filas++;
                 System.out.println("Contando filas: "+contador_de_filas);               
             }
             contador_de_filas++;
String ID_Actaul=Integer.toString(contador_de_filas);
jTextField_ID_Categoria.setText(ID_Actaul);          
         }
         catch (SQLException ex)
         {
             Logger.getLogger(Ventana_Categorias.class.getName()).log(Level.SEVERE, null, ex);
         }
}
    
private void PropiedadesTabla()
{
String columnas[] = {"Categorias"};

// Primero toma las filas pero no las tengo y pongo null
// Constructor de la Tabla
DefaultTableModel dft = new DefaultTableModel(null,columnas);
         try
         {
             Statement orden = cone2.createStatement();

//Monstrar Algo de una Base de Datos:

            ResultSet r = orden.executeQuery("Select* From Lista_de_Categorias");
            
             while (r.next())
             {  
                Object Filas[]={r.getString("Titulo_Categoria")};

// Le digo ahora que tome estas filas dentro de la tabla

            dft.addRow(Filas);
                
             }
             jTable_Listado_de_Categorias.setModel(dft);
           
         }
         catch (SQLException ex)
         {
             Logger.getLogger(Ventana_Categorias.class.getName()).log(Level.SEVERE, null, ex);
         }
}    
    
    
public Ventana_Categorias()
{
    initComponents();
    
    //Crea y carga al momento de cargar la ventana en pantalla.
    conex.CrearDB_Lista_de_Categorias();
    cone2= conex.CargarDB_Lista_de_Categorias();
    
   
    
    if(cone2!=null)
    {
    PropiedadesTabla();
    IniciarContador(contador_de_filas);
    
    //JOptionPane.showMessageDialog (null,"Mensaje","Titulo",JOptionPane.ERRROR_MESSAGE); 
    }
    
}

/**
 * This method is called from within the constructor to
 * initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
 * always regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Listado_de_Categorias = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextField_txtCuadroCategoria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_ID_Categoria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton_AgregarCategoria = new javax.swing.JButton();
        jButton_ModificarCategoria = new javax.swing.JButton();
        jButton_EliminarCategoria = new javax.swing.JButton();
        jButton_CerrarCategoria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable_Listado_de_Categorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane1.setViewportView(jTable_Listado_de_Categorias);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField_txtCuadroCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_txtCuadroCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_txtCuadroCategoria.setText("(Escribe la Nueva Categoria)");
        jTextField_txtCuadroCategoria.setFocusCycleRoot(true);
        jTextField_txtCuadroCategoria.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTextField_txtCuadroCategoriaMouseClicked(evt);
            }
        });
        jTextField_txtCuadroCategoria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField_txtCuadroCategoriaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Categorias");

        jTextField_ID_Categoria.setEditable(false);
        jTextField_ID_Categoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("ID:");

        jButton_AgregarCategoria.setText("+ Agregar");
        jButton_AgregarCategoria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_AgregarCategoriaActionPerformed(evt);
            }
        });

        jButton_ModificarCategoria.setText("* Modificar");

        jButton_EliminarCategoria.setText("- Eliminar");

        jButton_CerrarCategoria.setText("Cerrar");
        jButton_CerrarCategoria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_CerrarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton_AgregarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_ModificarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_ID_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_txtCuadroCategoria, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_CerrarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton_EliminarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_ID_Categoria)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_txtCuadroCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_AgregarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ModificarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_EliminarCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton_CerrarCategoria)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_AgregarCategoriaActionPerformed
    {//GEN-HEADEREND:event_jButton_AgregarCategoriaActionPerformed
// Al Presionar Agregar Categoria ocurre estas acciones:
// Debe Cargar la Base de Datos para luego poder consultar, modificarla o agregar nuevos elementos.  
// cone2=conex.CargarDB_Lista_de_Categorias();
// Cargo la base de datos mas arriba para tenerla disponible en todo.       
         if(cone2!=null)
  {
      try
      {
          Statement orden = cone2.createStatement();
          String crear = "Insert into Lista_de_Categorias(ID,Titulo_Categoria) Values("
                  + ""+jTextField_ID_Categoria.getText()+","
                  + "'"+jTextField_txtCuadroCategoria.getText()+ "')";
          
// Para ejecutar lo anterior se cree y actualice cada campo en la base de datos.
           orden.executeUpdate(crear);
          System.out.println("Registro Agregado OK");
          jTextField_txtCuadroCategoria.setText("");
          IniciarContador(contador_de_filas);
          PropiedadesTabla();
      }
      catch (SQLException ex)
      {
          System.out.println("Error:"+ex); 


          
      }
  }  
    }//GEN-LAST:event_jButton_AgregarCategoriaActionPerformed

    private void jTextField_txtCuadroCategoriaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField_txtCuadroCategoriaActionPerformed
    {//GEN-HEADEREND:event_jTextField_txtCuadroCategoriaActionPerformed

    }//GEN-LAST:event_jTextField_txtCuadroCategoriaActionPerformed

    private void jTextField_txtCuadroCategoriaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTextField_txtCuadroCategoriaMouseClicked
    {//GEN-HEADEREND:event_jTextField_txtCuadroCategoriaMouseClicked
          jTextField_txtCuadroCategoria.setText("");
    }//GEN-LAST:event_jTextField_txtCuadroCategoriaMouseClicked

    private void jButton_CerrarCategoriaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_CerrarCategoriaActionPerformed
    {//GEN-HEADEREND:event_jButton_CerrarCategoriaActionPerformed
//  Java: dispose() es usado para cerrar un jframe
        dispose();
    }//GEN-LAST:event_jButton_CerrarCategoriaActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[])
{
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
        {
            if ("Nimbus".equals(info.getName()))
            {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    }
    catch (ClassNotFoundException ex)
    {
        java.util.logging.Logger.getLogger(Ventana_Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
        java.util.logging.Logger.getLogger(Ventana_Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
        java.util.logging.Logger.getLogger(Ventana_Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
        java.util.logging.Logger.getLogger(Ventana_Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
    public void run()
    {
        new Ventana_Categorias().setVisible(true);
    }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AgregarCategoria;
    private javax.swing.JButton jButton_CerrarCategoria;
    private javax.swing.JButton jButton_EliminarCategoria;
    private javax.swing.JButton jButton_ModificarCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Listado_de_Categorias;
    private javax.swing.JTextField jTextField_ID_Categoria;
    private javax.swing.JTextField jTextField_txtCuadroCategoria;
    // End of variables declaration//GEN-END:variables
}
