/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EntornoGrafico;

import javax.swing.JOptionPane;

/**
 *
 * @author Res
 */
public class Ventana_Proveedores2 extends javax.swing.JFrame
{

String Bandera_Modificando="No";

/**
 * Creates new form Ventan_Proveedores2
 */
public Ventana_Proveedores2()
{
    initComponents();
}

/**
 * This method is called from within the constructor to
 * initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
 * always regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2_Codigo_Proveedor = new javax.swing.JLabel();
        jTextField_txtCodigo_Proveedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1_txtNombreApellido_Proveedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1_txtCalle_Proveedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_txtCalle_Numero_Proveedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1_txtTelefonoFijo_Proveedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2_txtTelefonoMovil_Proveedor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_TablaProveedores = new javax.swing.JTable();
        jLabel_Requerido_NombreyApellido = new javax.swing.JLabel();
        jLabel_Requerido_CalleNumero = new javax.swing.JLabel();
        jLabel_Requerido_Telefono = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_Empresa = new javax.swing.JTextField();
        jLabel_Requerido_Empresa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1_txtPiso_Proveedor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField1_txtEntreCalles_Proveedor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField1_txtGoogleMaps_Proveedor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField1_txtCODPOSTAL_Proveedor = new javax.swing.JTextField();
        jTextField1_txtProvincia_Proveedor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1_txtCiudad_Proveedor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField1_txtEmail_Proveedor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_txtAnotacionl_Proveedor = new javax.swing.JTextArea();
        jButton_AgregarRegistro = new javax.swing.JButton();
        jButton_ModificarRegistro = new javax.swing.JButton();
        jButton1_CerrarVentanAbierta = new javax.swing.JButton();
        jButton_EliminarRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RemitoAPP > Proveedores");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Proveedores");

        jLabel2_Codigo_Proveedor.setText("Código:");

        jTextField_txtCodigo_Proveedor.setEditable(false);
        jTextField_txtCodigo_Proveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_txtCodigo_Proveedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField_txtCodigo_ProveedorActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre y Apellido:");

        jTextField1_txtNombreApellido_Proveedor.setToolTipText("Campo Mínimo requerido (Requerido)");
        jTextField1_txtNombreApellido_Proveedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1_txtNombreApellido_ProveedorActionPerformed(evt);
            }
        });

        jLabel3.setText("Calle:");

        jTextField1_txtCalle_Proveedor.setToolTipText("Campo Mínimo requerido (Requerido)");

        jLabel6.setText("Numero:");

        jTextField1_txtCalle_Numero_Proveedor.setToolTipText("Campo Mínimo requerido (Requerido)");
        jTextField1_txtCalle_Numero_Proveedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1_txtCalle_Numero_ProveedorActionPerformed(evt);
            }
        });

        jLabel4.setText("Teléfono Fijo:");

        jTextField1_txtTelefonoFijo_Proveedor.setToolTipText("Campo Mínimo requerido (Requerido)");

        jLabel5.setText("Celular:");

        jTextField2_txtTelefonoMovil_Proveedor.setToolTipText("Campo Mínimo requerido (Requerido)");
        jTextField2_txtTelefonoMovil_Proveedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField2_txtTelefonoMovil_ProveedorActionPerformed(evt);
            }
        });

        jTable_TablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jTable_TablaProveedores.setEnabled(false);
        jTable_TablaProveedores.setFocusable(false);
        jTable_TablaProveedores.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTable_TablaProveedoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_TablaProveedores);

        jLabel_Requerido_NombreyApellido.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_Requerido_NombreyApellido.setText("(Requerido)");

        jLabel_Requerido_CalleNumero.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_Requerido_CalleNumero.setText("(Requerido)");

        jLabel_Requerido_Telefono.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_Requerido_Telefono.setText("(Requerido a lo sumo un Teléfono)");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Empresa:");

        jLabel_Requerido_Empresa.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_Requerido_Empresa.setText("(Requerido)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1_txtNombreApellido_Proveedor)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1_txtCalle_Proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1_txtCalle_Numero_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Requerido_NombreyApellido)
                                    .addComponent(jLabel_Requerido_CalleNumero)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1_txtTelefonoFijo_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2_txtTelefonoMovil_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Requerido_Telefono)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Requerido_Empresa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2_Codigo_Proveedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_txtCodigo_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2_Codigo_Proveedor)
                        .addComponent(jTextField_txtCodigo_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Requerido_Empresa))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1_txtNombreApellido_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Requerido_NombreyApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1_txtCalle_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1_txtCalle_Numero_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Requerido_CalleNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1_txtTelefonoFijo_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2_txtTelefonoMovil_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Requerido_Telefono))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Datos Basicos", jPanel1);

        jLabel7.setText("Piso / Depto :");

        jTextField1_txtPiso_Proveedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1_txtPiso_ProveedorActionPerformed(evt);
            }
        });

        jLabel8.setText("Entre Calles :");

        jLabel9.setText("GoogleMaps :");

        jLabel10.setText("Código Postal :");

        jLabel12.setText("Provincia :");

        jLabel13.setText("Ciudad :");

        jLabel14.setText("E-mail:");

        jTextField1_txtEmail_Proveedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1_txtEmail_ProveedorActionPerformed(evt);
            }
        });

        jLabel11.setText("Anotación (Un bloque de texto Libre):");

        jTextArea1_txtAnotacionl_Proveedor.setColumns(20);
        jTextArea1_txtAnotacionl_Proveedor.setRows(5);
        jScrollPane1.setViewportView(jTextArea1_txtAnotacionl_Proveedor);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1_txtPiso_Proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(jTextField1_txtEntreCalles_Proveedor)
                            .addComponent(jTextField1_txtGoogleMaps_Proveedor)
                            .addComponent(jTextField1_txtEmail_Proveedor)
                            .addComponent(jTextField1_txtCiudad_Proveedor)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField1_txtCODPOSTAL_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1_txtProvincia_Proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))))
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1_txtPiso_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1_txtEntreCalles_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1_txtGoogleMaps_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField1_txtCODPOSTAL_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField1_txtProvincia_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField1_txtCiudad_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField1_txtEmail_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Datos Opcionales", jPanel2);

        jButton_AgregarRegistro.setText("Agregar Proveedor");

        jButton_ModificarRegistro.setText("Modificar");

        jButton1_CerrarVentanAbierta.setText("Cerrar");
        jButton1_CerrarVentanAbierta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_CerrarVentanAbiertaActionPerformed(evt);
            }
        });

        jButton_EliminarRegistro.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_AgregarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_ModificarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_EliminarRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1_CerrarVentanAbierta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AgregarRegistro)
                    .addComponent(jButton_EliminarRegistro)
                    .addComponent(jButton_ModificarRegistro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1_CerrarVentanAbierta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_txtCodigo_ProveedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField_txtCodigo_ProveedorActionPerformed
    {//GEN-HEADEREND:event_jTextField_txtCodigo_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_txtCodigo_ProveedorActionPerformed

    private void jTextField1_txtNombreApellido_ProveedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1_txtNombreApellido_ProveedorActionPerformed
    {//GEN-HEADEREND:event_jTextField1_txtNombreApellido_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_txtNombreApellido_ProveedorActionPerformed

    private void jTextField1_txtCalle_Numero_ProveedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1_txtCalle_Numero_ProveedorActionPerformed
    {//GEN-HEADEREND:event_jTextField1_txtCalle_Numero_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_txtCalle_Numero_ProveedorActionPerformed

    private void jTextField2_txtTelefonoMovil_ProveedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField2_txtTelefonoMovil_ProveedorActionPerformed
    {//GEN-HEADEREND:event_jTextField2_txtTelefonoMovil_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_txtTelefonoMovil_ProveedorActionPerformed

    private void jTable_TablaProveedoresMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTable_TablaProveedoresMouseClicked
    {//GEN-HEADEREND:event_jTable_TablaProveedoresMouseClicked
        // al cliquear la tabla va tomar datos y mostrar en formulario
        Bandera_Modificando="Si";

        jButton_AgregarRegistro.setVisible(false);
        jButton_ModificarRegistro.setVisible(true);
        jButton_EliminarRegistro.setVisible(true);

        int seleccion=jTable_TablaProveedores.rowAtPoint(evt.getPoint());

        jTextField_txtCodigo_Proveedor.setText(String.valueOf(jTable_TablaProveedores.getValueAt(seleccion, 0)));
        jTextField_Empresa.setText (String.valueOf(jTable_TablaProveedores.getValueAt(seleccion, 1)));
        jTextField1_txtNombreApellido_Proveedor.setText (String.valueOf(jTable_TablaProveedores.getValueAt(seleccion, 2)));
        jTextField1_txtCalle_Proveedor.setText (String.valueOf(jTable_TablaProveedores.getValueAt(seleccion, 3)));
        jTextField1_txtCalle_Numero_Proveedor.setText (String.valueOf(jTable_TablaProveedores.getValueAt(seleccion, 4)));
        jTextField1_txtTelefonoFijo_Proveedor.setText (String.valueOf(jTable_TablaProveedores.getValueAt(seleccion, 5)));
        jTextField2_txtTelefonoMovil_Proveedor.setText (String.valueOf(jTable_TablaProveedores.getValueAt(seleccion, 6)));
        jTextField1_txtPiso_Proveedor.setText (String.valueOf(jTable_TablaProveedores.getValueAt(seleccion, 7)));
        jTextField1_txtEntreCalles_Proveedor.setText (String.valueOf(jTable_TablaProveedores.getValueAt(seleccion, 8)));
        jTextField1_txtGoogleMaps_Proveedor.setText (String.valueOf(jTable_TablaProveedores.getValueAt(seleccion, 9)));
        jTextField1_txtCODPOSTAL_Proveedor.setText (String.valueOf(jTable_TablaProveedores.getValueAt(seleccion, 10)));
        jTextField1_txtProvincia_Proveedor.setText (String.valueOf(jTable_TablaProveedores.getValueAt(seleccion, 11)));
        jTextField1_txtCiudad_Proveedor.setText (String.valueOf(jTable_TablaProveedores.getValueAt(seleccion, 12)));
        jTextField1_txtEmail_Proveedor.setText (String.valueOf(jTable_TablaProveedores.getValueAt(seleccion, 13)));
        jTextArea1_txtAnotacionl_Proveedor.setText (String.valueOf(jTable_TablaProveedores.getValueAt(seleccion, 14)));
        jTextField_Empresa.requestFocus();

    }//GEN-LAST:event_jTable_TablaProveedoresMouseClicked

    private void jTextField1_txtPiso_ProveedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1_txtPiso_ProveedorActionPerformed
    {//GEN-HEADEREND:event_jTextField1_txtPiso_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_txtPiso_ProveedorActionPerformed

    private void jTextField1_txtEmail_ProveedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1_txtEmail_ProveedorActionPerformed
    {//GEN-HEADEREND:event_jTextField1_txtEmail_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_txtEmail_ProveedorActionPerformed

    private void jButton1_CerrarVentanAbiertaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_CerrarVentanAbiertaActionPerformed
    {//GEN-HEADEREND:event_jButton1_CerrarVentanAbiertaActionPerformed
//  Java: dispose() es usado para cerrar un jframe
        if(jTextField_Empresa.getText().equals("")&& jTextField1_txtNombreApellido_Proveedor.getText().equals("")){
          dispose();  
        }else
        {
        String opcion[]={"Si", "Cancelar"};
        int eleccion =JOptionPane.showOptionDialog(this, "¿Esta seguro de Cerrar esta Ventana?", "Aviso", 0, 0, null, opcion, NORMAL);
       
        if(eleccion==JOptionPane.YES_OPTION)
        {
            dispose();
        }else if (eleccion==JOptionPane.NO_OPTION)
        {
            
        }  
        }
    }//GEN-LAST:event_jButton1_CerrarVentanAbiertaActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[])
{
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
        {
            if ("Nimbus".equals(info.getName()))
            {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    }
    catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
    {
        java.util.logging.Logger.getLogger(Ventana_Proveedores2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() ->
    {
        new Ventana_Proveedores2().setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_CerrarVentanAbierta;
    private javax.swing.JButton jButton_AgregarRegistro;
    private javax.swing.JButton jButton_EliminarRegistro;
    private javax.swing.JButton jButton_ModificarRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_Codigo_Proveedor;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Requerido_CalleNumero;
    private javax.swing.JLabel jLabel_Requerido_Empresa;
    private javax.swing.JLabel jLabel_Requerido_NombreyApellido;
    private javax.swing.JLabel jLabel_Requerido_Telefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_TablaProveedores;
    private javax.swing.JTextArea jTextArea1_txtAnotacionl_Proveedor;
    private javax.swing.JTextField jTextField1_txtCODPOSTAL_Proveedor;
    private javax.swing.JTextField jTextField1_txtCalle_Numero_Proveedor;
    private javax.swing.JTextField jTextField1_txtCalle_Proveedor;
    private javax.swing.JTextField jTextField1_txtCiudad_Proveedor;
    private javax.swing.JTextField jTextField1_txtEmail_Proveedor;
    private javax.swing.JTextField jTextField1_txtEntreCalles_Proveedor;
    private javax.swing.JTextField jTextField1_txtGoogleMaps_Proveedor;
    private javax.swing.JTextField jTextField1_txtNombreApellido_Proveedor;
    private javax.swing.JTextField jTextField1_txtPiso_Proveedor;
    private javax.swing.JTextField jTextField1_txtProvincia_Proveedor;
    private javax.swing.JTextField jTextField1_txtTelefonoFijo_Proveedor;
    private javax.swing.JTextField jTextField2_txtTelefonoMovil_Proveedor;
    private javax.swing.JTextField jTextField_Empresa;
    private javax.swing.JTextField jTextField_txtCodigo_Proveedor;
    // End of variables declaration//GEN-END:variables
}
