package EntornoGrafico;

import CodigoFuente.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Res
 */
public class Ventana_Productos extends javax.swing.JFrame
{

 Conexion conex = new Conexion();
 Connection cone2;
 Conexion conexion_BaseDatosCategorias = new Conexion();
 Conexion conexion_BaseDatosUbicaciones = new Conexion();
 Conexion conexion_BaseDatosMarcas = new Conexion();
 Conexion conexion_BaseDatosProveedores = new Conexion();
 Conexion conexion_Base_datos_Productos = new Conexion();

     // int contador_de_filas=1;
    private String SeBorroRegistro;
    private String TextoTemporal;
    private int Codigo_Producto_borrado;
    private Integer Comienza_desde_Aqui;
    private String Bandera_Modificando;
    private int seleccion;
    
    
public Ventana_Productos()
{
    initComponents();
    setIconImage(new ImageIcon(getClass().getResource("../Imagenes/Logo.png")).getImage());
    
    jTextField_Cuadro_Nombre.hasFocus();
   
   conexion_Base_datos_Productos.CrearDB_Base_datos_Productos();
   cone2= conex.CargarDB_Base_datos_Productos();
   
        CBoxCategorias();
        CBoxUbicacion();
        CBoxMarcas();        
        CBoxProveedores();
        
     //   jButton_ModificarProducto.setVisible(false);

     //   jButton_EliminarProducto.setVisible(false);
        
 
        
        
          if(cone2!=null)
    {
PropiedadesTabla();

    }
}

/**
 * This method is called from within the constructor to
 * initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
 * always regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Pasos = new javax.swing.JTabbedPane();
        panel_categoria_marca_ubicacion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_lista_de_categoria = new javax.swing.JComboBox<>();
        jButton_actualizar_lista_de_categoria = new javax.swing.JButton();
        jButton_abrir_categoria = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_lista_de_marcas = new javax.swing.JComboBox<>();
        jButton_actualizar_lista_de_marcas = new javax.swing.JButton();
        jButton_abrir_marcas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_lista_de_ubicaciones = new javax.swing.JComboBox<>();
        jButton_actualizar_lista_de_ubicaciones = new javax.swing.JButton();
        jButton_abrir_ubicaciones = new javax.swing.JButton();
        jTextField_Cuadro_Nombre1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Codigo_de_Productos = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        panel_cantidad_y_costo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panel_configuracion_caja_atado = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        panel_proveedor = new javax.swing.JPanel();
        jLabel_NombreProveedor = new javax.swing.JLabel();
        jComboBox_lista_de_proveedores = new javax.swing.JComboBox<>();
        jButton_actualizar_lista_de_proveedores = new javax.swing.JButton();
        jButton_abrir_proeedores = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel_EscribirEmpresadelProveedor = new javax.swing.JLabel();
        jLabel_EscribirNombreyApellidodelProveedor = new javax.swing.JLabel();
        panel_tabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Listado_de_Productos = new javax.swing.JTable();
        jTextField_Cuadro_Nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton_CerrarVentana = new javax.swing.JButton();
        jButton_AgregarProducto = new javax.swing.JButton();
        jButton_ModificarProducto = new javax.swing.JButton();
        jButton_EliminarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Productos");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setResizable(false);
        setSize(getPreferredSize());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos");

        panel_categoria_marca_ubicacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Categoria");

        jButton_actualizar_lista_de_categoria.setText("Actualizar");
        jButton_actualizar_lista_de_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizar_lista_de_categoriaActionPerformed(evt);
            }
        });

        jButton_abrir_categoria.setText("+");
        jButton_abrir_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_abrir_categoriaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Marca");

        jButton_actualizar_lista_de_marcas.setText("Actualizar");
        jButton_actualizar_lista_de_marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizar_lista_de_marcasActionPerformed(evt);
            }
        });

        jButton_abrir_marcas.setText("+");
        jButton_abrir_marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_abrir_marcasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ubicación");

        jButton_actualizar_lista_de_ubicaciones.setText("Actualizar");
        jButton_actualizar_lista_de_ubicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizar_lista_de_ubicacionesActionPerformed(evt);
            }
        });

        jButton_abrir_ubicaciones.setText("+");
        jButton_abrir_ubicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_abrir_ubicacionesActionPerformed(evt);
            }
        });

        jTextField_Cuadro_Nombre1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField_Cuadro_Nombre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Cuadro_Nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Cuadro_Nombre1ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Código:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel_Codigo_de_Productos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Codigo_de_Productos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Codigo_de_Productos.setText("0");
        jLabel_Codigo_de_Productos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Nombre del Producto ");

        javax.swing.GroupLayout panel_categoria_marca_ubicacionLayout = new javax.swing.GroupLayout(panel_categoria_marca_ubicacion);
        panel_categoria_marca_ubicacion.setLayout(panel_categoria_marca_ubicacionLayout);
        panel_categoria_marca_ubicacionLayout.setHorizontalGroup(
            panel_categoria_marca_ubicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_categoria_marca_ubicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_categoria_marca_ubicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_categoria_marca_ubicacionLayout.createSequentialGroup()
                        .addGroup(panel_categoria_marca_ubicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_categoria_marca_ubicacionLayout.createSequentialGroup()
                                .addComponent(jTextField_Cuadro_Nombre1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Codigo_de_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_categoria_marca_ubicacionLayout.createSequentialGroup()
                                .addComponent(jComboBox_lista_de_categoria, 0, 224, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_actualizar_lista_de_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_abrir_categoria))
                            .addGroup(panel_categoria_marca_ubicacionLayout.createSequentialGroup()
                                .addComponent(jComboBox_lista_de_marcas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_actualizar_lista_de_marcas, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_abrir_marcas))
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_categoria_marca_ubicacionLayout.createSequentialGroup()
                                .addComponent(jComboBox_lista_de_ubicaciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_actualizar_lista_de_ubicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_abrir_ubicaciones)))
                        .addContainerGap())))
        );
        panel_categoria_marca_ubicacionLayout.setVerticalGroup(
            panel_categoria_marca_ubicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_categoria_marca_ubicacionLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(panel_categoria_marca_ubicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Cuadro_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_categoria_marca_ubicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_Codigo_de_Productos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_categoria_marca_ubicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_lista_de_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_actualizar_lista_de_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_abrir_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_categoria_marca_ubicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_lista_de_marcas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_actualizar_lista_de_marcas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_abrir_marcas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_categoria_marca_ubicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_lista_de_ubicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_actualizar_lista_de_ubicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_abrir_ubicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pasos.addTab("Paso 1", panel_categoria_marca_ubicacion);

        panel_cantidad_y_costo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cantidad y Costo");

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("0");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Unidades:");

        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("0");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Costo x Unidad:");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Cajas:");

        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("0");

        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("0");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Costo x Cajas:");

        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("0");

        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("0");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Atados:");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Costo x Atados:");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout panel_cantidad_y_costoLayout = new javax.swing.GroupLayout(panel_cantidad_y_costo);
        panel_cantidad_y_costo.setLayout(panel_cantidad_y_costoLayout);
        panel_cantidad_y_costoLayout.setHorizontalGroup(
            panel_cantidad_y_costoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_cantidad_y_costoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_cantidad_y_costoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_cantidad_y_costoLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_cantidad_y_costoLayout.createSequentialGroup()
                        .addGroup(panel_cantidad_y_costoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_cantidad_y_costoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(jTextField9))))
                .addGroup(panel_cantidad_y_costoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_cantidad_y_costoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panel_cantidad_y_costoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cantidad_y_costoLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cantidad_y_costoLayout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_cantidad_y_costoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        panel_cantidad_y_costoLayout.setVerticalGroup(
            panel_cantidad_y_costoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cantidad_y_costoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_cantidad_y_costoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cantidad_y_costoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cantidad_y_costoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        Pasos.addTab("Paso 2", panel_cantidad_y_costo);

        panel_configuracion_caja_atado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Configuraciones");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Una Caja tiene");

        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("0");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Unidades");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Un Atado son");

        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("0");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Unidades");

        javax.swing.GroupLayout panel_configuracion_caja_atadoLayout = new javax.swing.GroupLayout(panel_configuracion_caja_atado);
        panel_configuracion_caja_atado.setLayout(panel_configuracion_caja_atadoLayout);
        panel_configuracion_caja_atadoLayout.setHorizontalGroup(
            panel_configuracion_caja_atadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_configuracion_caja_atadoLayout.createSequentialGroup()
                .addGroup(panel_configuracion_caja_atadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_configuracion_caja_atadoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panel_configuracion_caja_atadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_configuracion_caja_atadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jTextField14))
                        .addGap(18, 18, 18)
                        .addGroup(panel_configuracion_caja_atadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        panel_configuracion_caja_atadoLayout.setVerticalGroup(
            panel_configuracion_caja_atadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_configuracion_caja_atadoLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_configuracion_caja_atadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_configuracion_caja_atadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(216, 216, 216))
        );

        Pasos.addTab("Paso 3", panel_configuracion_caja_atado);

        panel_proveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_NombreProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_NombreProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_NombreProveedor.setText("Proveedor");

        jButton_actualizar_lista_de_proveedores.setText("Actualizar");
        jButton_actualizar_lista_de_proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizar_lista_de_proveedoresActionPerformed(evt);
            }
        });

        jButton_abrir_proeedores.setText("+");
        jButton_abrir_proeedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_abrir_proeedoresActionPerformed(evt);
            }
        });

        jLabel10.setText("Empresa:");

        jLabel14.setText("Nombre y Apellido:");

        jLabel_EscribirEmpresadelProveedor.setText("---");

        jLabel_EscribirNombreyApellidodelProveedor.setText("----");

        javax.swing.GroupLayout panel_proveedorLayout = new javax.swing.GroupLayout(panel_proveedor);
        panel_proveedor.setLayout(panel_proveedorLayout);
        panel_proveedorLayout.setHorizontalGroup(
            panel_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_proveedorLayout.createSequentialGroup()
                .addGroup(panel_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_proveedorLayout.createSequentialGroup()
                        .addComponent(jLabel_NombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_actualizar_lista_de_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_abrir_proeedores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_lista_de_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_proveedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_proveedorLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_EscribirNombreyApellidodelProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_proveedorLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_EscribirEmpresadelProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        panel_proveedorLayout.setVerticalGroup(
            panel_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_proveedorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_lista_de_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_actualizar_lista_de_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_abrir_proeedores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel_EscribirEmpresadelProveedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_proveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel_EscribirNombreyApellidodelProveedor))
                .addGap(219, 219, 219))
        );

        Pasos.addTab("Paso 4", panel_proveedor);

        jTable_Listado_de_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Listado_de_Productos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable_Listado_de_Productos);

        jTextField_Cuadro_Nombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField_Cuadro_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Cuadro_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Cuadro_NombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Buscar:");

        javax.swing.GroupLayout panel_tablaLayout = new javax.swing.GroupLayout(panel_tabla);
        panel_tabla.setLayout(panel_tablaLayout);
        panel_tablaLayout.setHorizontalGroup(
            panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panel_tablaLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jTextField_Cuadro_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_tablaLayout.setVerticalGroup(
            panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Cuadro_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_tablaLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        Pasos.addTab("Lista Completa", panel_tabla);

        jButton_CerrarVentana.setText("Cerrar");
        jButton_CerrarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_CerrarVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CerrarVentanaActionPerformed(evt);
            }
        });

        jButton_AgregarProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_AgregarProducto.setText("Agregar Nuevo Producto");
        jButton_AgregarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_AgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarProductoActionPerformed(evt);
            }
        });

        jButton_ModificarProducto.setText("Modificar");
        jButton_ModificarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModificarProductoActionPerformed(evt);
            }
        });

        jButton_EliminarProducto.setText("Eliminar");
        jButton_EliminarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_AgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_ModificarProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_EliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_CerrarVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Pasos))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pasos, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_AgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ModificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_EliminarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_CerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AgregarProductoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_AgregarProductoActionPerformed
    {//GEN-HEADEREND:event_jButton_AgregarProductoActionPerformed

       agregar_producto_nuevo();             
    }//GEN-LAST:event_jButton_AgregarProductoActionPerformed

    private void jTextField_Cuadro_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Cuadro_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Cuadro_NombreActionPerformed

    private void jButton_abrir_proeedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_abrir_proeedoresActionPerformed
       //Proeedores
        Ventana_Proveedores ventanabierta = new Ventana_Proveedores();
        ventanabierta.setLocationRelativeTo(getParent());
        ventanabierta.setVisible(true); 
    }//GEN-LAST:event_jButton_abrir_proeedoresActionPerformed

    private void jButton_abrir_ubicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_abrir_ubicacionesActionPerformed
       //Ubicaciones 
        Ventana_Ubicaciones ventanabierta = new Ventana_Ubicaciones();
        ventanabierta.setLocationRelativeTo(getParent());
        ventanabierta.setVisible(true); 
    }//GEN-LAST:event_jButton_abrir_ubicacionesActionPerformed

    private void jButton_abrir_marcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_abrir_marcasActionPerformed
       //Marcas
        Ventana_Marcas ventanabierta = new Ventana_Marcas();
        ventanabierta.setLocationRelativeTo(getParent());
        ventanabierta.setVisible(true); 
    }//GEN-LAST:event_jButton_abrir_marcasActionPerformed

    private void jButton_abrir_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_abrir_categoriaActionPerformed
    //Categoria
        Ventana_Categorias ventanabierta = new Ventana_Categorias();
        ventanabierta.setLocationRelativeTo(getParent());
        ventanabierta.setVisible(true); 
    }//GEN-LAST:event_jButton_abrir_categoriaActionPerformed

    private void jButton_CerrarVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CerrarVentanaActionPerformed
    dispose();
    }//GEN-LAST:event_jButton_CerrarVentanaActionPerformed

    private void jTextField_Cuadro_Nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Cuadro_Nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Cuadro_Nombre1ActionPerformed

    private void jButton_ModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModificarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ModificarProductoActionPerformed

    private void jButton_actualizar_lista_de_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizar_lista_de_categoriaActionPerformed
    jComboBox_lista_de_categoria.removeAllItems();
        CBoxCategorias();
    }//GEN-LAST:event_jButton_actualizar_lista_de_categoriaActionPerformed

    private void jButton_actualizar_lista_de_marcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizar_lista_de_marcasActionPerformed
        jComboBox_lista_de_marcas.removeAllItems();
        CBoxMarcas();        
    }//GEN-LAST:event_jButton_actualizar_lista_de_marcasActionPerformed

    private void jButton_actualizar_lista_de_ubicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizar_lista_de_ubicacionesActionPerformed
        jComboBox_lista_de_ubicaciones.removeAllItems();
        CBoxUbicacion();    
        CBoxProveedores();
    }//GEN-LAST:event_jButton_actualizar_lista_de_ubicacionesActionPerformed

    private void jButton_actualizar_lista_de_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizar_lista_de_proveedoresActionPerformed
        jComboBox_lista_de_proveedores.removeAllItems();  
        CBoxProveedores();
    }//GEN-LAST:event_jButton_actualizar_lista_de_proveedoresActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[])
{
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
        {
            if ("Nimbus".equals(info.getName()))
            {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    }
    catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
    {
        java.util.logging.Logger.getLogger(Ventana_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
     //</editor-fold>

    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() ->
    {
        new Ventana_Productos().setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Pasos;
    private javax.swing.JButton jButton_AgregarProducto;
    private javax.swing.JButton jButton_CerrarVentana;
    private javax.swing.JButton jButton_EliminarProducto;
    private javax.swing.JButton jButton_ModificarProducto;
    private javax.swing.JButton jButton_abrir_categoria;
    private javax.swing.JButton jButton_abrir_marcas;
    private javax.swing.JButton jButton_abrir_proeedores;
    private javax.swing.JButton jButton_abrir_ubicaciones;
    private javax.swing.JButton jButton_actualizar_lista_de_categoria;
    private javax.swing.JButton jButton_actualizar_lista_de_marcas;
    private javax.swing.JButton jButton_actualizar_lista_de_proveedores;
    private javax.swing.JButton jButton_actualizar_lista_de_ubicaciones;
    private javax.swing.JComboBox<String> jComboBox_lista_de_categoria;
    private javax.swing.JComboBox<String> jComboBox_lista_de_marcas;
    private javax.swing.JComboBox<String> jComboBox_lista_de_proveedores;
    private javax.swing.JComboBox<String> jComboBox_lista_de_ubicaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Codigo_de_Productos;
    private javax.swing.JLabel jLabel_EscribirEmpresadelProveedor;
    private javax.swing.JLabel jLabel_EscribirNombreyApellidodelProveedor;
    private javax.swing.JLabel jLabel_NombreProveedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Listado_de_Productos;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextField_Cuadro_Nombre;
    private javax.swing.JTextField jTextField_Cuadro_Nombre1;
    private javax.swing.JPanel panel_cantidad_y_costo;
    private javax.swing.JPanel panel_categoria_marca_ubicacion;
    private javax.swing.JPanel panel_configuracion_caja_atado;
    private javax.swing.JPanel panel_proveedor;
    private javax.swing.JPanel panel_tabla;
    // End of variables declaration//GEN-END:variables

 private void CBoxCategorias()
 {
       jComboBox_lista_de_categoria.removeAllItems();
   //  conex.CrearDB_Lista_de_Categorias();
     cone2=conex.CargarDB_Lista_de_Categorias(); 
     conexion_BaseDatosCategorias.CrearDB_Lista_de_Categorias();
   //  conexion_BaseDatosCategorias.CargarDB_Lista_de_Categorias();
   Statement orden;
     try
     {
         orden = cone2.createStatement();
         ResultSet r=orden.executeQuery("Select* From Lista_de_Categorias");
         while (r.next())
         {             
             jComboBox_lista_de_categoria.addItem(r.getString("Titulo_Categoria"));
         }
     }
     catch (SQLException ex)
     {
         Logger.getLogger(Ventana_Productos.class.getName()).log(Level.SEVERE, null, ex);
     }

     
 }
  private void CBoxProveedores()
 {
          jComboBox_lista_de_proveedores.removeAllItems();
    cone2= conex.CargarDB_Base_datos_Proveedores();
conex.CrearDB_Base_datos_Proveedores();
   Statement orden;
     try
     {
         orden = cone2.createStatement();
         ResultSet r=orden.executeQuery("Select* From ListadeProveedores");
         while (r.next())
         {             
             jComboBox_lista_de_proveedores.addItem(r.getString("Codigo_Proveedor"));
         }
     }
     catch (SQLException ex)
     {
         Logger.getLogger(Ventana_Productos.class.getName()).log(Level.SEVERE, null, ex);
     }

     
 }   
 private void CBoxUbicacion()
 {
      jComboBox_lista_de_ubicaciones.removeAllItems();
     conexion_BaseDatosCategorias.CrearDB_Base_datos_Ubicaciones();
     cone2= conex.CargarDB_Base_datos_Ubicaciones();
   Statement orden;
     try
     {
         orden = cone2.createStatement();
         ResultSet r=orden.executeQuery("Select* From Lista_de_Ubicaciones");
         while (r.next())
         {             
             jComboBox_lista_de_ubicaciones.addItem(r.getString("Lugar"));
         }
     }
     catch (SQLException ex)
     {
         Logger.getLogger(Ventana_Productos.class.getName()).log(Level.SEVERE, null, ex);
     }

     
 }   

    private void CBoxMarcas()
    {
            jComboBox_lista_de_marcas.removeAllItems();
    conexion_BaseDatosMarcas.CrearDB_Base_datos_Marcas();
    cone2= conexion_BaseDatosMarcas.CargarDB_Base_datos_Marcas();
   Statement orden;
     try
     {
         orden = cone2.createStatement();
         ResultSet r=orden.executeQuery("Select* From Lista_de_Marcas");
         while (r.next())
         {             
             jComboBox_lista_de_marcas.addItem(r.getString("Marcas"));
         }
     }
     catch (SQLException ex)
     {
         Logger.getLogger(Ventana_Productos.class.getName()).log(Level.SEVERE, null, ex);
     }

      
    }
public int id_incrementable()
{
    int id=0;
    PreparedStatement ps =null;
    //  cone2=conexion_Base_datos_Productos.CargarDB_Base_datos_Productos();
            cone2=conex.CargarDB_Base_datos_Productos();
    try
    {
      Statement orden = cone2.createStatement();
      ResultSet r = orden.executeQuery("Select MAX(Codigo_Producto) From Listadeproductos");
        while (r.next())
        {            
                    id=r.getInt(1)+1;

        }
        System.out.println("Id Maximo:"+id);
        
            }
    catch (Exception ex)
    {
        System.out.println("Error:"+ex);
    }
    finally
    {
        try
        {
            ps.close();
            
            //DesconectarBasededatos Falta
        }
        catch (Exception e)
        {
        }
    
    }
    
        if(SeBorroRegistro=="SI")
    {
                        System.out.println("Se Borro un registro recien:"+SeBorroRegistro+"La Id era:"+Codigo_Producto_borrado );
     id=Comienza_desde_Aqui;   
    }
    
        return id;
    }

      private void PropiedadesTabla()
{
  cone2=conexion_Base_datos_Productos.CargarDB_Base_datos_Productos();
String columnas[] = {"COD","Producto"};

if(!"SI".equals(SeBorroRegistro)){
int id=id_incrementable();
jLabel_Codigo_de_Productos.setText(String.valueOf(id));    
}
// Primero toma las filas pero no las tengo y pongo null
// Constructor de la Tabla
DefaultTableModel dft = new DefaultTableModel(null,columnas);

         try
         {
//Monstrar Algo de una Base de Datos:
    try (Statement orden = cone2.createStatement())
    {
        //Monstrar Algo de una Base de Datos:
        
        ResultSet r = orden.executeQuery("Select* From Listadeproductos");
        
        while (r.next())
        {
            Object Filas[]={r.getString("Codigo_Producto"),r.getString("Nombre_Producto")};
            
// Le digo ahora que tome estas filas dentro de la tabla

dft.addRow(Filas);

        }
        jTable_Listado_de_Productos.setModel(dft);
        r.close();
    }
           
         }
         catch (SQLException ex)
         {
             Logger.getLogger(Ventana_Marcas.class.getName()).log(Level.SEVERE, null, ex);
         }
}   

    private void agregar_producto_nuevo() {
       // Accion Boton Agregar
// Cargar Base de Datos        
        cone2=conexion_Base_datos_Productos.CargarDB_Base_datos_Productos();

// controlar base de datos
if (cone2!=null)
        {
            try
            {
                Statement orden=cone2.createStatement();
                
                String crear = "Insert Into Listadeproductos(Codigo_Producto,Nombre_Producto,Categoria_Producto,Ubicacion_Producto,Marca,Unidades_Producto,Cajas_Producto,Una_Caja_Tiene_Producto,Atados_Producto,Un_Atado_Tiene_Producto,CostoxUnidad_Producto,CostoxCaja__Producto,CostoxAtado,Codigo_Provedor) "
                        + "values("+jLabel_Codigo_de_Productos.getText()+",'"+jTextField_Cuadro_Nombre.getText()+"')";
                
            }
            catch (SQLException ex)
            {
                System.out.println("Error en carga datos");
                Logger.getLogger(Ventana_Productos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }

    private void Cargar_Panel_1(String estado) {
        if ("apagado".equals(estado)) 
        {
        panel_categoria_marca_ubicacion.setVisible(false);
        estado="prendido";
        }else
        {
        estado="apagado";    
        panel_categoria_marca_ubicacion.setVisible(true);      
        }

    }

    private void Cargar_Panel_2(String estado) {
            if ("apagado".equals(estado)) 
        {
        panel_cantidad_y_costo.setVisible(false);
        estado="prendido";
        }else
        { 
        panel_cantidad_y_costo.setVisible(true);
        estado="apagado"; 
        }
    }

    private void Cargar_Panel_3(String estado) {
            if ("apagado".equals(estado)) 
        {
        panel_configuracion_caja_atado.setVisible(false); 
        estado="prendido";
        }else
        {  
        panel_configuracion_caja_atado.setVisible(true);
        estado="apagado";
        }
    }

    private void Cargar_Panel_4(String estado) {
            if ("apagado".equals(estado)) 
        {
        panel_proveedor.setVisible(false);
        estado="prendido";
        }else
        {   
        panel_proveedor.setVisible(false);
        estado="prendido";
        }
    }
}
